name: run tests and collect coverage

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install hatch
        run: python -m pip install hatch
      - name: Run tests
        run: hatch run test:test
      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
